# Generated by Django 5.0 on 2023-12-25 13:06

import django.core.validators
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_gender_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[store.validators.NationalCodeValidator()], verbose_name='National code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('a', 'Accepted'), ('r', 'Rejected')], default='w', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='store/cv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='CV'),
        ),
    ]
