# Generated by Django 5.0 on 2024-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_address_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company name'),
            preserve_default=False,
        ),
    ]
