# Generated by Django 5.0.3 on 2024-03-09 16:13

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productimage_name_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='national_code',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[store.validators.NationalCodeValidator()], verbose_name='National code'),
        ),
    ]
