# Generated by Django 5.0.3 on 2024-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_seller_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict, verbose_name='Specifications'),
        ),
    ]
