# Generated by Django 5.0.3 on 2024-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Specifications'),
        ),
    ]
