# Generated by Django 5.0.3 on 2024-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_comment_level_comment_lft_comment_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3, null=True, verbose_name='Rating'),
        ),
    ]
