# Generated by Django 5.0.3 on 2024-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewer',
            field=models.PositiveIntegerField(default=0, verbose_name='Viewer'),
        ),
    ]
