# Generated by Django 5.0.3 on 2024-04-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0017_product_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'store'), ('model', 'customer')), models.Q(('app_label', 'store'), ('model', 'seller')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], null=True, verbose_name='Rating'),
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='store.comment', verbose_name='Comment')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'store'), ('model', 'customer')), models.Q(('app_label', 'store'), ('model', 'seller')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Comment dislike',
                'verbose_name_plural': 'Comment dislikes',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Modified datetime')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.comment', verbose_name='Comment')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'store'), ('model', 'customer')), models.Q(('app_label', 'store'), ('model', 'seller')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Comment like',
                'verbose_name_plural': 'Comment likes',
            },
        ),
    ]
