# Generated by Django 5.0.3 on 2024-04-08 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_comment_content_type_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/product_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='File extension not allowed. Allowed extensions include  .jpg, .jpeg .png')], verbose_name='Image'),
        ),
    ]
