# Generated by Django 5.0.4 on 2024-06-08 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_zarinpal_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreaseWalletCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal authority')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal ref_id')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='increase_wallet_credits', to='store.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Increase wallet credit',
                'verbose_name_plural': 'Increase wallet credits',
            },
        ),
    ]
