# Generated by Django 5.0.4 on 2024-06-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_increasewalletcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='increasewalletcredit',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
    ]
