# Generated by Django 5.0.4 on 2024-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_increasewalletcredit_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('o', 'Online'), ('w', 'Wallet')], default='o', max_length=1, verbose_name='Payment method'),
        ),
    ]
