# Generated by Django 4.2.7 on 2023-12-05 12:03

import core.models
import core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Request id')),
                ('phone', models.CharField(max_length=11, validators=[core.validators.PhoneValidator()], verbose_name='Phone')),
                ('password', models.CharField(max_length=4, verbose_name='Password')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created datetime')),
                ('expired_datetime', models.DateTimeField(default=core.models.get_expired_datetime, verbose_name='Expired datetime')),
            ],
            options={
                'verbose_name': 'One time password',
                'verbose_name_plural': 'One time passwords',
            },
        ),
    ]
